version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb://mongodb:27017
      - DB_USER=root
      - DB_PASSWORD=pass123
      - DB_NAME=taxi
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d

volumes:
  mongodata:
